// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: fission/v1/image.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageGenerate_ImageGenerate_FullMethodName   = "/fission.v1.ImageGenerate/ImageGenerate"
	ImageGenerate_ImagedDowngrade_FullMethodName = "/fission.v1.ImageGenerate/ImagedDowngrade"
)

// ImageGenerateClient is the client API for ImageGenerate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageGenerateClient interface {
	ImageGenerate(ctx context.Context, in *SynthesisParamRequest, opts ...grpc.CallOption) (*SynthesisResponse, error)
	ImagedDowngrade(ctx context.Context, in *SynthesisParamRequest, opts ...grpc.CallOption) (*SynthesisResponse, error)
}

type imageGenerateClient struct {
	cc grpc.ClientConnInterface
}

func NewImageGenerateClient(cc grpc.ClientConnInterface) ImageGenerateClient {
	return &imageGenerateClient{cc}
}

func (c *imageGenerateClient) ImageGenerate(ctx context.Context, in *SynthesisParamRequest, opts ...grpc.CallOption) (*SynthesisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynthesisResponse)
	err := c.cc.Invoke(ctx, ImageGenerate_ImageGenerate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageGenerateClient) ImagedDowngrade(ctx context.Context, in *SynthesisParamRequest, opts ...grpc.CallOption) (*SynthesisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynthesisResponse)
	err := c.cc.Invoke(ctx, ImageGenerate_ImagedDowngrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageGenerateServer is the server API for ImageGenerate service.
// All implementations must embed UnimplementedImageGenerateServer
// for forward compatibility.
type ImageGenerateServer interface {
	ImageGenerate(context.Context, *SynthesisParamRequest) (*SynthesisResponse, error)
	ImagedDowngrade(context.Context, *SynthesisParamRequest) (*SynthesisResponse, error)
	mustEmbedUnimplementedImageGenerateServer()
}

// UnimplementedImageGenerateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageGenerateServer struct{}

func (UnimplementedImageGenerateServer) ImageGenerate(context.Context, *SynthesisParamRequest) (*SynthesisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImageGenerate not implemented")
}
func (UnimplementedImageGenerateServer) ImagedDowngrade(context.Context, *SynthesisParamRequest) (*SynthesisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImagedDowngrade not implemented")
}
func (UnimplementedImageGenerateServer) mustEmbedUnimplementedImageGenerateServer() {}
func (UnimplementedImageGenerateServer) testEmbeddedByValue()                       {}

// UnsafeImageGenerateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageGenerateServer will
// result in compilation errors.
type UnsafeImageGenerateServer interface {
	mustEmbedUnimplementedImageGenerateServer()
}

func RegisterImageGenerateServer(s grpc.ServiceRegistrar, srv ImageGenerateServer) {
	// If the following call pancis, it indicates UnimplementedImageGenerateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageGenerate_ServiceDesc, srv)
}

func _ImageGenerate_ImageGenerate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesisParamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageGenerateServer).ImageGenerate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageGenerate_ImageGenerate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageGenerateServer).ImageGenerate(ctx, req.(*SynthesisParamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageGenerate_ImagedDowngrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesisParamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageGenerateServer).ImagedDowngrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageGenerate_ImagedDowngrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageGenerateServer).ImagedDowngrade(ctx, req.(*SynthesisParamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageGenerate_ServiceDesc is the grpc.ServiceDesc for ImageGenerate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageGenerate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fission.v1.ImageGenerate",
	HandlerType: (*ImageGenerateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImageGenerate",
			Handler:    _ImageGenerate_ImageGenerate_Handler,
		},
		{
			MethodName: "ImagedDowngrade",
			Handler:    _ImageGenerate_ImagedDowngrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fission/v1/image.proto",
}
