// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: fission/v1/nxcloud.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NXCloud_UserAttendInfo_FullMethodName  = "/fission.v1.NXCloud/UserAttendInfo"
	NXCloud_UserAttendInfo2_FullMethodName = "/fission.v1.NXCloud/UserAttendInfo2"
)

// NXCloudClient is the client API for NXCloud service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NXCloudClient interface {
	UserAttendInfo(ctx context.Context, in *UserAttendInfoRequest, opts ...grpc.CallOption) (*UserAttendInfoResponse, error)
	// UserAttendInfo2 implements v1.NXCloudHTTPServer.
	// webhook
	UserAttendInfo2(ctx context.Context, in *UserAttendInfoRequest, opts ...grpc.CallOption) (*UserAttendInfoResponse, error)
}

type nXCloudClient struct {
	cc grpc.ClientConnInterface
}

func NewNXCloudClient(cc grpc.ClientConnInterface) NXCloudClient {
	return &nXCloudClient{cc}
}

func (c *nXCloudClient) UserAttendInfo(ctx context.Context, in *UserAttendInfoRequest, opts ...grpc.CallOption) (*UserAttendInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAttendInfoResponse)
	err := c.cc.Invoke(ctx, NXCloud_UserAttendInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nXCloudClient) UserAttendInfo2(ctx context.Context, in *UserAttendInfoRequest, opts ...grpc.CallOption) (*UserAttendInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAttendInfoResponse)
	err := c.cc.Invoke(ctx, NXCloud_UserAttendInfo2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NXCloudServer is the server API for NXCloud service.
// All implementations must embed UnimplementedNXCloudServer
// for forward compatibility.
type NXCloudServer interface {
	UserAttendInfo(context.Context, *UserAttendInfoRequest) (*UserAttendInfoResponse, error)
	// UserAttendInfo2 implements v1.NXCloudHTTPServer.
	// webhook
	UserAttendInfo2(context.Context, *UserAttendInfoRequest) (*UserAttendInfoResponse, error)
	mustEmbedUnimplementedNXCloudServer()
}

// UnimplementedNXCloudServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNXCloudServer struct{}

func (UnimplementedNXCloudServer) UserAttendInfo(context.Context, *UserAttendInfoRequest) (*UserAttendInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAttendInfo not implemented")
}
func (UnimplementedNXCloudServer) UserAttendInfo2(context.Context, *UserAttendInfoRequest) (*UserAttendInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAttendInfo2 not implemented")
}
func (UnimplementedNXCloudServer) mustEmbedUnimplementedNXCloudServer() {}
func (UnimplementedNXCloudServer) testEmbeddedByValue()                 {}

// UnsafeNXCloudServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NXCloudServer will
// result in compilation errors.
type UnsafeNXCloudServer interface {
	mustEmbedUnimplementedNXCloudServer()
}

func RegisterNXCloudServer(s grpc.ServiceRegistrar, srv NXCloudServer) {
	// If the following call pancis, it indicates UnimplementedNXCloudServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NXCloud_ServiceDesc, srv)
}

func _NXCloud_UserAttendInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAttendInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NXCloudServer).UserAttendInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NXCloud_UserAttendInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NXCloudServer).UserAttendInfo(ctx, req.(*UserAttendInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NXCloud_UserAttendInfo2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAttendInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NXCloudServer).UserAttendInfo2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NXCloud_UserAttendInfo2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NXCloudServer).UserAttendInfo2(ctx, req.(*UserAttendInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NXCloud_ServiceDesc is the grpc.ServiceDesc for NXCloud service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NXCloud_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fission.v1.NXCloud",
	HandlerType: (*NXCloudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserAttendInfo",
			Handler:    _NXCloud_UserAttendInfo_Handler,
		},
		{
			MethodName: "UserAttendInfo2",
			Handler:    _NXCloud_UserAttendInfo2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fission/v1/nxcloud.proto",
}
