// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fission-basic/internal/biz"
	"fission-basic/internal/conf"
	"fission-basic/internal/data"
	"fission-basic/internal/pkg/feishu"
	"fission-basic/internal/pkg/queue"
	"fission-basic/internal/pkg/redis"
	"fission-basic/internal/server"
	"fission-basic/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, bootstrap *conf.Bootstrap, confData *conf.Data, business *conf.Business, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	studentRepo := data.NewStudent(dataData, logger)
	studentUsecase := biz.NewStudentUsecase(studentRepo, logger)
	waMsgRetryRepo := data.NewWaMsgRetry(dataData, logger)
	clusterClient := redis.NewRedisClient(confData)
	redisService := redis.NewRedisService(clusterClient, logger, confData, business)
	waMsgSendRepo := data.NewWaMsgSend(dataData, redisService, business, logger)
	imageGenerate := biz.NewImageGenerate(business, logger, redisService)
	waMsgService := biz.NewWaMsgService(confData, logger, bootstrap, waMsgRetryRepo, waMsgSendRepo, redisService, imageGenerate)
	activityInfoRepo := data.NewActivityInfo(dataData, logger, redisService)
	activityInfoUsecase := biz.NewActivityInfoUsecase(activityInfoRepo, logger, bootstrap)
	userInfoRepo := data.NewUserInfo(dataData, logger)
	userInfoUsecase := biz.NewUserInfoUsecase(userInfoRepo, logger)
	studentService := service.NewStudentService(confData, studentUsecase, waMsgService, waMsgSendRepo, activityInfoUsecase, userInfoUsecase, logger, business)
	nxCloudRepo := data.NewNXCloud(dataData, logger)
	msgRepo := data.NewMsg(dataData, logger)
	official := queue.NewOfficialQueue(clusterClient, confData)
	unOfficial := queue.NewUnOfficialQueue(clusterClient, confData)
	renewMsg := queue.NewRenewMsg(clusterClient, confData)
	callMsg := queue.NewCallMsg(clusterClient, confData)
	repeatHelp := queue.NewRepeatHelp(clusterClient, confData)
	rally := data.NewRally(dataData, logger)
	officialRallyRepo := data.NewOfficialRally(rally)
	nxCloudUsecase := biz.NewNxCLoudUsecase(nxCloudRepo, msgRepo, logger, official, unOfficial, renewMsg, callMsg, repeatHelp, waMsgService, waMsgSendRepo, officialRallyRepo, business, redisService)
	gw := queue.NewGW(clusterClient, confData)
	gwRecall := queue.NewGWRecal(clusterClient, confData)
	gwUnknown := queue.NewGWUnknown(clusterClient, confData)
	nxCloudService, cleanup2 := service.NewNxCloudService(nxCloudUsecase, logger, confData, business, redisService, gw, gwRecall, gwUnknown, activityInfoUsecase)
	systemConfigRepo := data.NewSystemConfig(dataData, logger)
	systemConfigUsecase := biz.NewSystemConfigUsecase(systemConfigRepo, logger)
	cdkService := service.NewCDKService(confData, userInfoUsecase, systemConfigUsecase, business, redisService, logger)
	initRepo := data.NewInitDB(dataData, logger)
	init := biz.NewInit(initRepo, logger)
	helpCodeRepo := data.NewHelpCode(dataData, logger)
	helpCodeUsecase := biz.NewHelpCodeUsecase(helpCodeRepo, logger)
	feishuFeishu := feishu.NewFeishu(confData, logger)
	initService := service.NewInitService(init, redisService, helpCodeUsecase, feishuFeishu, logger)
	imageService := service.NewImageService(imageGenerate, logger)
	uploadUserInfoRepo := data.NewUploadUserInfo(dataData, logger)
	waUserScoreRepo := data.NewWaUserScore(dataData, logger)
	waMsgReceivedRepo := data.NewWaMsgReceived(dataData, logger)
	pushEventSendMessageRepo := data.NewPushEventSendMessage(dataData, logger)
	pushEvent4UserRepo := data.NewPushEvent4User(dataData, logger)
	countLimitRepo := data.NewCountLimit(dataData, logger)
	drainageJob := biz.NewDrainageJob(waUserScoreRepo, uploadUserInfoRepo, userInfoRepo, waMsgReceivedRepo, pushEventSendMessageRepo, pushEvent4UserRepo, countLimitRepo, redisService, business, bootstrap, logger)
	userJoinGroupRepo := data.NewUserJoinGroup(dataData, logger)
	emailReportRepo := data.NewEmailReport(dataData, logger)
	emailReportJob := biz.NewEmailReportJob(systemConfigRepo, waMsgSendRepo, userInfoRepo, userJoinGroupRepo, emailReportRepo, redisService, logger, business, confData)
	uploadService := service.NewUploadService(uploadUserInfoRepo, drainageJob, emailReportJob, redisService, business, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, studentService, nxCloudService, cdkService, initService, imageService, uploadService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
